projects:
  aws/account:
    repo: git@github.com:hops-ops/aws-account.git

  aws/actions-connector:
    repo: git@github.com:hops-ops/aws-actions-connector.git

  aws/auto-eks-cluster:
    repo: git@github.com:hops-ops/aws-auto-eks-cluster.git

  aws/cost-report:
    repo: git@github.com:hops-ops/aws-cost-report.git

  aws/foundation:
    repo: git@github.com:hops-ops/aws-foundation.git

  aws/identity-center:
    repo: git@github.com:hops-ops/aws-identity-center.git

  aws/ipam:
    repo: git@github.com:hops-ops/aws-ipam.git

  aws/irsa:
    repo: git@github.com:hops-ops/aws-irsa.git

  aws/network:
    repo: git@github.com:hops-ops/aws-network.git

  aws/organization:
    repo: git@github.com:hops-ops/aws-organization.git

  aws/pod-identity:
    repo: git@github.com:hops-ops/aws-pod-identity.git

  aws/ram-share:
    repo: git@github.com:hops-ops/aws-ram-share.git

  aws/spot-feed:
    repo: git@github.com:hops-ops/aws-spot-feed.git

  aws/smtp-sender:
    repo: git@github.com:hops-ops/aws-smtp-sender.git

  stacks/aws/lbc:
    repo: git@github.com:hops-ops/aws-lbc-stack.git

  stacks/aws/crossplane:
    repo: git@github.com:hops-ops/aws-crossplane-stack.git

  stacks/aws/dns:
    repo: git@github.com:hops-ops/aws-dns-stack.git

  stacks/aws/observe:
    repo: git@github.com:hops-ops/aws-observe-stack.git

  stacks/aws/secret:
    repo: git@github.com:hops-ops/aws-secret-stack.git

  stacks/cloudflare/dns:
    repo: git@github.com:hops-ops/cloudflare-dns-stack.git

  stacks/k8s/analytics:
    repo: git@github.com:hops-ops/analytics-stack.git

  stacks/k8s/auth:
    repo: git@github.com:hops-ops/auth-stack.git

  stacks/k8s/cert:
    repo: git@github.com:hops-ops/cert-stack.git

  stacks/k8s/gitops:
    repo: git@github.com:hops-ops/gitops-stack.git

  stacks/k8s/flux-gitops:
    repo: git@github.com:hops-ops/flux-gitops-stack.git

  stacks/k8s/istio:
    repo: git@github.com:hops-ops/istio-stack.git

  stacks/k8s/knative:
    repo: git@github.com:hops-ops/knative-stack.git

  stacks/k8s/observe:
    repo: git@github.com:hops-ops/observe-stack.git

  stacks/k8s/policy:
    repo: git@github.com:hops-ops/policy-stack.git

  stacks/k8s/psql:
    repo: git@github.com:hops-ops/psql-stack.git

  stacks/k8s/security:
    repo: git@github.com:hops-ops/security-stack.git

  stacks/k8s/volume-snapshot:
    repo: git@github.com:hops-ops/volume-snapshot-stack.git

  charts/openpanel-chart:
    repo: git@github.com:hops-ops/openpanel-chart.git

  providers/terraform-provider-openpanel:
    repo: git@github.com:hops-ops/terraform-provider-openpanel.git

  providers/provider-openpanel:
    repo: git@github.com:hops-ops/provider-openpanel.git

  tenant:
    repo: git@github.com:hops-ops/tenant.git
